// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstApp.Data;

namespace MyFirstApp.Migrations
{
    [DbContext(typeof(schoolDbContext))]
    [Migration("20220418002126_AddAmenitiesTable")]
    partial class AddAmenitiesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyFirstApp.Models.Amenity", b =>
                {
                    b.Property<int>("amenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("amenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            amenityId = 1,
                            name = "Spa"
                        },
                        new
                        {
                            amenityId = 2,
                            name = "Toiletries"
                        },
                        new
                        {
                            amenityId = 3,
                            name = "Shaving Cream"
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.Hotel", b =>
                {
                    b.Property<int>("hotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            hotelId = 1,
                            address = "5th Circle",
                            city = "Amman",
                            name = "Sheraton",
                            phoneNum = "0795396245",
                            state = "Amman"
                        },
                        new
                        {
                            hotelId = 2,
                            address = "Abo Shouman Str",
                            city = "Amman",
                            name = "Kempinski",
                            phoneNum = "0784326751",
                            state = "Amman"
                        },
                        new
                        {
                            hotelId = 3,
                            address = "University Str",
                            city = "Irbid",
                            name = "Seven Days",
                            phoneNum = "0774326571",
                            state = "Irbid"
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            roomId = 1,
                            layout = "master room",
                            nickname = "Special Room"
                        },
                        new
                        {
                            roomId = 2,
                            layout = "Room with a big pool",
                            nickname = "VIP Room"
                        },
                        new
                        {
                            roomId = 3,
                            layout = "Normal room",
                            nickname = "Standard Room"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
